<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['en' => 'Afghanistan', 'ar' => 'أفغانستان'],
            ['en' => 'Albania', 'ar' => 'ألبانيا'],
            ['en' => 'Algeria', 'ar' => 'الجزائر'],
            ['en' => 'Andorra', 'ar' => 'أندورا'],
            ['en' => 'Angola', 'ar' => 'أنغولا'],
            ['en' => 'Antigua and Barbuda', 'ar' => 'أنتيغوا وبربودا'],
            ['en' => 'Argentina', 'ar' => 'الأرجنتين'],
            ['en' => 'Armenia', 'ar' => 'أرمينيا'],
            ['en' => 'Australia', 'ar' => 'أستراليا'],
            ['en' => 'Austria', 'ar' => 'النمسا'],
            ['en' => 'Azerbaijan', 'ar' => 'أذربيجان'],
            ['en' => 'Bahamas', 'ar' => 'الباهاما'],
            ['en' => 'Bahrain', 'ar' => 'البحرين'],
            ['en' => 'Bangladesh', 'ar' => 'بنغلاديش'],
            ['en' => 'Barbados', 'ar' => 'بربادوس'],
            ['en' => 'Belarus', 'ar' => 'بيلاروسيا'],
            ['en' => 'Belgium', 'ar' => 'بلجيكا'],
            ['en' => 'Belize', 'ar' => 'بليز'],
            ['en' => 'Benin', 'ar' => 'بنين'],
            ['en' => 'Bhutan', 'ar' => 'بوتان'],
            ['en' => 'Bolivia', 'ar' => 'بوليفيا'],
            ['en' => 'Bosnia and Herzegovina', 'ar' => 'البوسنة والهرسك'],
            ['en' => 'Botswana', 'ar' => 'بوتسوانا'],
            ['en' => 'Brazil', 'ar' => 'البرازيل'],
            ['en' => 'Brunei', 'ar' => 'بروناي'],
            ['en' => 'Bulgaria', 'ar' => 'بلغاريا'],
            ['en' => 'Burkina Faso', 'ar' => 'بوركينا فاسو'],
            ['en' => 'Burundi', 'ar' => 'بوروندي'],
            ['en' => 'Cabo Verde', 'ar' => 'الرأس الأخضر'],
            ['en' => 'Cambodia', 'ar' => 'كمبوديا'],
            ['en' => 'Cameroon', 'ar' => 'الكاميرون'],
            ['en' => 'Canada', 'ar' => 'كندا'],
            ['en' => 'Central African Republic', 'ar' => 'جمهورية أفريقيا الوسطى'],
            ['en' => 'Chad', 'ar' => 'تشاد'],
            ['en' => 'Chile', 'ar' => 'تشيلي'],
            ['en' => 'China', 'ar' => 'الصين'],
            ['en' => 'Colombia', 'ar' => 'كولومبيا'],
            ['en' => 'Comoros', 'ar' => 'جزر القمر'],
            ['en' => 'Congo', 'ar' => 'الكونغو'],
            ['en' => 'Costa Rica', 'ar' => 'كوستاريكا'],
            ['en' => 'Croatia', 'ar' => 'كرواتيا'],
            ['en' => 'Cuba', 'ar' => 'كوبا'],
            ['en' => 'Cyprus', 'ar' => 'قبرص'],
            ['en' => 'Czech Republic', 'ar' => 'جمهورية التشيك'],
            ['en' => 'Denmark', 'ar' => 'الدنمارك'],
            ['en' => 'Djibouti', 'ar' => 'جيبوتي'],
            ['en' => 'Dominica', 'ar' => 'دومينيكا'],
            ['en' => 'Dominican Republic', 'ar' => 'جمهورية الدومينيكان'],
            ['en' => 'Ecuador', 'ar' => 'الإكوادور'],
            ['en' => 'Egypt', 'ar' => 'مصر'],
            ['en' => 'El Salvador', 'ar' => 'السلفادور'],
            ['en' => 'Equatorial Guinea', 'ar' => 'غينيا الاستوائية'],
            ['en' => 'Eritrea', 'ar' => 'إريتريا'],
            ['en' => 'Estonia', 'ar' => 'إستونيا'],
            ['en' => 'Eswatini', 'ar' => 'إسواتيني'],
            ['en' => 'Ethiopia', 'ar' => 'إثيوبيا'],
            ['en' => 'Fiji', 'ar' => 'فيجي'],
            ['en' => 'Finland', 'ar' => 'فنلندا'],
            ['en' => 'France', 'ar' => 'فرنسا'],
            ['en' => 'Gabon', 'ar' => 'الغابون'],
            ['en' => 'Gambia', 'ar' => 'غامبيا'],
            ['en' => 'Georgia', 'ar' => 'جورجيا'],
            ['en' => 'Germany', 'ar' => 'ألمانيا'],
            ['en' => 'Ghana', 'ar' => 'غانا'],
            ['en' => 'Greece', 'ar' => 'اليونان'],
            ['en' => 'Grenada', 'ar' => 'غرينادا'],
            ['en' => 'Guatemala', 'ar' => 'غواتيمالا'],
            ['en' => 'Guinea', 'ar' => 'غينيا'],
            ['en' => 'Guinea-Bissau', 'ar' => 'غينيا بيساو'],
            ['en' => 'Guyana', 'ar' => 'غيانا'],
            ['en' => 'Haiti', 'ar' => 'هايتي'],
            ['en' => 'Honduras', 'ar' => 'هندوراس'],
            ['en' => 'Hungary', 'ar' => 'هنغاريا'],
            ['en' => 'Iceland', 'ar' => 'آيسلندا'],
            ['en' => 'India', 'ar' => 'الهند'],
            ['en' => 'Indonesia', 'ar' => 'إندونيسيا'],
            ['en' => 'Iran', 'ar' => 'إيران'],
            ['en' => 'Iraq', 'ar' => 'العراق'],
            ['en' => 'Ireland', 'ar' => 'أيرلندا'],
            ['en' => 'Palastine', 'ar' => 'فلسطين'],
            ['en' => 'Italy', 'ar' => 'إيطاليا'],
            ['en' => 'Jamaica', 'ar' => 'جامايكا'],
            ['en' => 'Japan', 'ar' => 'اليابان'],
            ['en' => 'Jordan', 'ar' => 'الأردن'],
            ['en' => 'Kazakhstan', 'ar' => 'كازاخستان'],
            ['en' => 'Kenya', 'ar' => 'كينيا'],
            ['en' => 'Kiribati', 'ar' => 'كيريباتي'],
            ['en' => 'Kuwait', 'ar' => 'الكويت'],
            ['en' => 'Kyrgyzstan', 'ar' => 'قيرغيزستان'],
            ['en' => 'Laos', 'ar' => 'لاوس'],
            ['en' => 'Latvia', 'ar' => 'لاتفيا'],
            ['en' => 'Lebanon', 'ar' => 'لبنان'],
            ['en' => 'Lesotho', 'ar' => 'ليسوتو'],
            ['en' => 'Liberia', 'ar' => 'ليبيريا'],
            ['en' => 'Libya', 'ar' => 'ليبيا'],
            ['en' => 'Liechtenstein', 'ar' => 'ليختنشتاين'],
            ['en' => 'Lithuania', 'ar' => 'ليتوانيا'],
            ['en' => 'Luxembourg', 'ar' => 'لوكسمبورغ'],
            ['en' => 'Madagascar', 'ar' => 'مدغشقر'],
            ['en' => 'Malawi', 'ar' => 'مالاوي'],
            ['en' => 'Malaysia', 'ar' => 'ماليزيا'],
            ['en' => 'Maldives', 'ar' => 'المالديف'],
            ['en' => 'Mali', 'ar' => 'مالي'],
            ['en' => 'Malta', 'ar' => 'مالطا'],
            ['en' => 'Marshall Islands', 'ar' => 'جزر مارشال'],
            ['en' => 'Mauritania', 'ar' => 'موريتانيا'],
            ['en' => 'Mauritius', 'ar' => 'موريشيوس'],
            ['en' => 'Mexico', 'ar' => 'المكسيك'],
            ['en' => 'Micronesia', 'ar' => 'ميكرونيزيا'],
            ['en' => 'Moldova', 'ar' => 'مولدوفا'],
            ['en' => 'Monaco', 'ar' => 'موناكو'],
            ['en' => 'Mongolia', 'ar' => 'منغوليا'],
            ['en' => 'Montenegro', 'ar' => 'الجبل الأسود'],
            ['en' => 'Morocco', 'ar' => 'المغرب'],
            ['en' => 'Mozambique', 'ar' => 'موزمبيق'],
            ['en' => 'Myanmar', 'ar' => 'ميانمار'],
            ['en' => 'Namibia', 'ar' => 'ناميبيا'],
            ['en' => 'Nauru', 'ar' => 'ناورو'],
            ['en' => 'Nepal', 'ar' => 'نيبال'],
            ['en' => 'Netherlands', 'ar' => 'هولندا'],
            ['en' => 'New Zealand', 'ar' => 'نيوزيلندا'],
            ['en' => 'Nicaragua', 'ar' => 'نيكاراغوا'],
            ['en' => 'Niger', 'ar' => 'النيجر'],
            ['en' => 'Nigeria', 'ar' => 'نيجيريا'],
            ['en' => 'North Macedonia', 'ar' => 'مقدونيا الشمالية'],
            ['en' => 'Norway', 'ar' => 'النرويج'],
            ['en' => 'Oman', 'ar' => 'عمان'],
            ['en' => 'Pakistan', 'ar' => 'باكستان'],
            ['en' => 'Palau', 'ar' => 'بالاو'],
            ['en' => 'Panama', 'ar' => 'بنما'],
            ['en' => 'Papua New Guinea', 'ar' => 'بابوا غينيا الجديدة'],
            ['en' => 'Paraguay', 'ar' => 'باراغواي'],
            ['en' => 'Peru', 'ar' => 'بيرو'],
            ['en' => 'Philippines', 'ar' => 'الفلبين'],
            ['en' => 'Poland', 'ar' => 'بولندا'],
            ['en' => 'Portugal', 'ar' => 'البرتغال'],
            ['en' => 'Qatar', 'ar' => 'قطر'],
            ['en' => 'Romania', 'ar' => 'رومانيا'],
            ['en' => 'Russia', 'ar' => 'روسيا'],
            ['en' => 'Rwanda', 'ar' => 'رواندا'],
            ['en' => 'Saint Kitts and Nevis', 'ar' => 'سانت كيتس ونيفيس'],
            ['en' => 'Saint Lucia', 'ar' => 'سانت لوسيا'],
            ['en' => 'Saint Vincent and the Grenadines', 'ar' => 'سانت فنسنت وجزر غرينادين'],
            ['en' => 'Samoa', 'ar' => 'ساموا'],
            ['en' => 'San Marino', 'ar' => 'سان مارينو'],
            ['en' => 'Sao Tome and Principe', 'ar' => 'ساو تومي وبرينسيب'],
            ['en' => 'Saudi Arabia', 'ar' => 'المملكة العربية السعودية'],
            ['en' => 'Senegal', 'ar' => 'السنغال'],
            ['en' => 'Serbia', 'ar' => 'صربيا'],
            ['en' => 'Seychelles', 'ar' => 'سيشيل'],
            ['en' => 'Sierra Leone', 'ar' => 'سيراليون'],
            ['en' => 'Singapore', 'ar' => 'سنغافورة'],
            ['en' => 'Slovakia', 'ar' => 'سلوفاكيا'],
            ['en' => 'Slovenia', 'ar' => 'سلوفينيا'],
            ['en' => 'Solomon Islands', 'ar' => 'جزر سليمان'],
            ['en' => 'Somalia', 'ar' => 'الصومال'],
            ['en' => 'South Africa', 'ar' => 'جنوب أفريقيا'],
            ['en' => 'South Sudan', 'ar' => 'جنوب السودان'],
            ['en' => 'Spain', 'ar' => 'إسبانيا'],
            ['en' => 'Sri Lanka', 'ar' => 'سريلانكا'],
            ['en' => 'Sudan', 'ar' => 'السودان'],
            ['en' => 'Suriname', 'ar' => 'سورينام'],
            ['en' => 'Sweden', 'ar' => 'السويد'],
            ['en' => 'Switzerland', 'ar' => 'سويسرا'],
            ['en' => 'Syria', 'ar' => 'سوريا'],
            ['en' => 'Taiwan', 'ar' => 'تايوان'],
            ['en' => 'Tajikistan', 'ar' => 'طاجيكستان'],
            ['en' => 'Tanzania', 'ar' => 'تنزانيا'],
            ['en' => 'Thailand', 'ar' => 'تايلاند'],
            ['en' => 'Timor-Leste', 'ar' => 'تيمور الشرقية'],
            ['en' => 'Togo', 'ar' => 'توغو'],
            ['en' => 'Tonga', 'ar' => 'تونغا'],
            ['en' => 'Trinidad and Tobago', 'ar' => 'ترينيداد وتوباغو'],
            ['en' => 'Tunisia', 'ar' => 'تونس'],
            ['en' => 'Turkey', 'ar' => 'تركيا'],
            ['en' => 'Turkmenistan', 'ar' => 'تركمانستان'],
            ['en' => 'Tuvalu', 'ar' => 'توفالو'],
            ['en' => 'Uganda', 'ar' => 'أوغندا'],
            ['en' => 'Ukraine', 'ar' => 'أوكرانيا'],
            ['en' => 'United Arab Emirates', 'ar' => 'الإمارات العربية المتحدة'],
            ['en' => 'United Kingdom', 'ar' => 'المملكة المتحدة'],
            ['en' => 'United States of America', 'ar' => 'الولايات المتحدة الأمريكية'],
            ['en' => 'Uruguay', 'ar' => 'أوروغواي'],
            ['en' => 'Uzbekistan', 'ar' => 'أوزبكستان'],
            ['en' => 'Vanuatu', 'ar' => 'فانواتو'],
            ['en' => 'Vatican City', 'ar' => 'مدينة الفاتيكان'],
            ['en' => 'Venezuela', 'ar' => 'فنزويلا'],
            ['en' => 'Vietnam', 'ar' => 'فيتنام'],
            ['en' => 'Yemen', 'ar' => 'اليمن'],
            ['en' => 'Zambia', 'ar' => 'زامبيا'],
            ['en' => 'Zimbabwe', 'ar' => 'زيمبابوي'],
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'name_en' => $country['en'],
                'name_ar' => $country['ar'],
            ]);
        }
    }
}
